"""Initial migration

Revision ID: bf049891445f
Revises: 
Create Date: 2025-01-18 23:55:28.158905

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf049891445f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('batch_department')
    op.drop_table('years')
    op.drop_table('bd_ss_courses')
    op.drop_table('departments')
    op.drop_table('batches')
    op.drop_table('courses')
    op.drop_table('bd_semester_session')
    op.drop_table('semesters')
    op.drop_table('sessions')
    op.drop_table('datesheet')
    op.drop_table('teachers_courses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=200),
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('ur_id',
               existing_type=mysql.VARCHAR(length=40),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'student'"))
        batch_op.alter_column('status',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.create_foreign_key(None, 'users_roles', ['ur_id'], ['id'])

    with op.batch_alter_table('users_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=80), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=40), nullable=False))
        batch_op.drop_column('role')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('ur_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=40),
               existing_nullable=False,
               existing_server_default=sa.text("'student'"))
        batch_op.alter_column('password',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=False,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)

    op.create_table('teachers_courses',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('subject_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('batch_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('semester_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('year_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('datesheet',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('exam_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), server_default=sa.text('current_timestamp()'), nullable=False),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sessions',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.ENUM('fall', 'spring', '', ''), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('semesters',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('slug', mysql.VARCHAR(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('bd_semester_session',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('bd_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('semester_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('session_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('end_date', sa.DATE(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('courses',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('type', mysql.ENUM('lecture', 'lab'), nullable=False),
    sa.Column('credit_hours', mysql.ENUM('1', '2', '3', '4', '5', '6'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('batches',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('session', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('start_year_id', mysql.INTEGER(display_width=4), server_default=sa.text('current_timestamp()'), autoincrement=False, nullable=False),
    sa.Column('slug', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('departments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('bd_ss_courses',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('bss_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('course_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('is_compulsory', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('years',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('year', mysql.YEAR(display_width=4), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('batch_department',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('batch_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('department_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
